document.addEventListener('DOMContentLoaded', () =>{
    const flashcards = [
        {question: "To the affected area", answer: "AA"},
        {question: "Both", answer: "AB"},
        {question: "Before a meal", answer: "AC"},
        {question: "After a meal", answer: "PC"},
        {question: "With a meal", answer: "WAC"},
        {question: "With meals", answer: "WC"},
        {question: "Administer", answer: "ADM"},
        {question: "In affected ear", answer: "AEA"},
        {question: "In affected eyes", answer: "AEY"},
        {question: "After initial dose", answer: "AIDO"},
        {question: "If opioid emergency persist, alternate nostrils", answer: "ALN"},
        {question: "Ampule", answer: "AMP"},
        {question: "at onset", answer: "AOS"},
        {question: "apply", answer: "APP"},
        {question: "Applicatorful", answer: "APL"},
        {question: "Apply 1 thin layer", answer: "ATL"},
        {question: "At night", answer: "ATN"},
        {question: "Both ears", answer: "AU"},
        {question: "Use 1 ampule via nebulizer", answer: "AVN"},
        {question: "Before", answer: "B"},
        {question: "Bedtime", answer: "BED"},
        {question: "Twice daily for 10 days", answer: "BF10"},
        {question: "Twice daily for 5 days", answer: "BF5"},
        {question: "Blood Glucose", answer: "BG"},
        {question: "Twice Daily", answer: "BID"},
        {question: "Twice Monthly", answer: "BIM"},
        {question: "Twice a week", answer: "BIW"},
        {question: "Bowel Movement", answer: "BM"},
        {question: "Blood Pressure", answer: "BP"},
        {question: "Breakthrough pain", answer: "BTP"},
        {question: "Capsule", answer: "C"},
        {question: "Take one capsule every __ hours", answer: "CAP,#"},
        {question: "Capfuls", answer: "CFL"},
        {question: "Cough and congestion", answer: "CNC"},
        {question: "Contents of 1 packet", answer: "CNTS"},
        {question: "Congestion", answer: "COG"},
        {question: "Consecutive", answer: "CONS"},
        {question: "Continue", answer: "CONT"},
        {question: "For Cough", answer: "COU"},
        {question: "Chest Pain", answer: "CP"},
        {question: "Take _ capsules every _ hours", answer: "CPS,#,#"},
        {question: "Crush", answer: "CRU"},
        {question: "Capsules", answer: "CS"},
        {question: "Constipation", answer: "CSTP"},
        {question: "Chew and swallow", answer: "CSW"},
        {question: "Daily", answer: "D"},
        {question: "Diastolic blood pressure", answer: "BDP"},
        {question: "Dissolve", answer: "DIS"},
        {question: "Dissolve _ tablets in water", answer: "DIW,_"},
        {question: "Dropperful", answer: "DRP"},
        {question: "May repeat every 2-3 min if emergency persists", answer: "EMR"},
        {question: "Evening", answer: "EVE"},
        {question: "Externally", answer: "EXT"},
        {question: "As needed for fever", answer: "FEV"},
        {question: "As needed for fever and pain", answer: "FEVP"},
        {question: "Five times daily", answer: "FID"},
        {question: "Follow package directions", answer: "FPD"},
        {question: "Drops", answer: "GTS"},
        {question: "Drop", answer: "GTT"},
        {question: "Headache", answer: "HA"},
        {question: "At bedtime", answer: "HS"},
        {question: "Insert", answer: "I"},
        {question: "In each nostril", answer: "IEN"},
        {question: "In the muscle", answer: "IM"},
        {question: "Immediately", answer: "IMM"},
        {question: "Inhale _ puffs every _ hours", answer: "INH,#,#"},
        {question: "Instill", answer: "INT"},
        {question: "In the morning", answer: "ITM"},
        {question: "Insert one applicatorful vaginally at bedtime", answer: "IVB"},
        {question: "Insert one suppository vaginally at bedtime", answer: "IVS"},
        {question: "In the left ear", answer: "LEA"},
        {question: "In the right ear", answer: "REA"},
        {question: "In the left eye", answer: "LEY"},
        {question: "In the right eye", answer: "REY"},
        {question: "Month", answer: "M"},
        {question: "May cause drowsiness", answer: "MCD"},
        {question: "Maximum daily dose is", answer: "MDD"},
        {question: "Monday", answer: "MON"},
        {question: "Muscle spasms", answer: "MSP"},
        {question: "Into upper arm or thigh muscle", answer: "MUS"},
        {question: "Monday, Wednesday, Friday", answer: "MWF"},
        {question: "Mix", answer: "MX"},
        {question: "MX granules in 15 to 30 ml of room temp tap", answer: "MXG"},
        {question: "For Nausea", answer: "N"},
        {question: "Nebulizer", answer: "NEB"},
        {question: "For nerves", answer: "NER"},
        {question: "Nostril", answer: "NOS"},
        {question: "Nothing by mouth", answer: "NPO"},
        {question: "Nasally", answer: "NLY"},
        {question: "Not to exceed", answer: "NTE"},
        {question: "Nights", answer: "NTS"},
        {question: "For nausea and vomiting", answer: "NV"},
        {question: "1 daily for a full cycle, stop for 1 week then repeat", answer: ""},
        {question: "Right eye", answer: "OD"},
        {question: "Left eye", answer: "OS"},
        {question: "Both eyes", answer: "OU"},
        {question: "On an empty stomach", answer: "OES"},
        {question: "In one nostril", answer: "ONS"},
        {question: "For pain", answer: "P"},
        {question: "Patch", answer: "PA"},
        {question: "By mouth", answer: "PO"},
        {question: "As needed for anxiety", answer: "PRA"},
        {question: "As needed for", answer: "PRF"},
        {question: "As needed", answer: "PRN"},
        {question: "Procedure", answer: "PRO"},
        {question: "Prior to appointment", answer: "PTA"},
        {question: "Every", answer: "Q"},
        {question: "Every 3 Months", answer: "Q3M"},
        {question: "Every day for 10 days", answer: "QD10"},
        {question: "Three times daily for 10 days", answer: "TFW"},
        {question: "Every day for 5 days", answer: "QD5"},
        {question: "Three times daily for 5 days", answer: "TF5"},
        {question: "4 days a week", answer: "QDW"},
        {question: "3 days a week", answer: "TDW"},
        {question: "Every month", answer: "QM"},
        {question: "Every other month", answer: "QOM"},
        {question: "Every week", answer: "QW"},
        {question: "Every other week", answer: "QOW"},
        {question: "Every day", answer: "QD"},
        {question: "Every other day", answer: "QOD"},
        {question: "One day a week", answer: "QW"},
        {question: "Rectal", answer: "R"},
        {question: "Rectally", answer: "REC"},
        {question: "Refrigerate", answer: "RF"},
        {question: "Rinse mouth", answer: "RM"},
        {question: "Swish and swallow", answer: "SAS"},
        {question: "Systolic blood pressure", answer: "SBP"},
        {question: "Under the skin", answer: "SC"},
        {question: "Sleep", answer: "SLP"},
        {question: "Sunday", answer: "SND"},
        {question: "Soak", answer: "SOA"},
        {question: "Shortness of breath", answer: "SOB"},
        {question: "Spray", answer: "SPR"},
        {question: "Suppository", answer: "SUP"},
        {question: "Subcutaneous", answer: "SQ"},
        {question: "One-half", answer: "SS"},
        {question: "Swish and spit", answer: "SSP"},
        {question: "Shake liquid well", answer: "SW"},
        {question: "Shake well and refridgerate", answer: "SWR"},
        {question: "Tablet", answer: "T"},
        {question: "Take one tablet every _ hours", answer: "Tab,#"},
        {question: "Until all taken", answer: "TAT"},
        {question: "Today", answer: "TAY"},
        {question: "Take _ tablets every _ hours", answer: "TABS,#,#"},
        {question: "Three times daily", answer: "TID"},
        {question: "Take", answer: "tk"},
        {question: "One tablet under tongue as needed for chest pain; Nitroglycerin", answer: "TNT"},
        {question: "Tablets", answer: "TS"},
        {question: "Use", answer: "U"},
        {question: "Ointment", answer: "UNG"},
        {question: "Units", answer: "UNI"},
        {question: "Under the tongue", answer: "UNT"},
        {question: "Unwrap", answer: "UNW"},
        {question: "As directed", answer: "UTD"},
        {question: "Vaginal", answer: "VA"},
        {question: "In the vagina", answer: "VAG"},
        {question: "Vomiting", answer: "VOM"},
        {question: "Use 1 vial via nebulizer", answer: "VVN"},
        {question: "While awake", answer: "WA"},
    ];

    let currentCard = 0;

    const flashcardElement = document.getElementById('flashcard');
    const questionElement = document.getElementById('question');
    const answerElement = document.getElementById('answer');

    function displayCard() {
        questionElement.textContent = flashcards[currentCard].question;
        answerElement.textContent = flashcards[currentCard].answer;
        flashcardElement.classList.remove('is-flipped')
    }

    document.getElementById('flip-card').addEventListener('click', () => {
        flashcardElement.classList.toggle('is-flipped')
    });

    document.getElementById('next-card').addEventListener('click', () => {
        currentCard = (currentCard + 1) % flashcards.length;
        displayCard();
    })

    displayCard();
});
